-- Insert Services into the services table
-- This will populate the database with 10 different repair services

INSERT INTO services (
    name, 
    name_ar, 
    description, 
    description_ar, 
    category, 
    image_url, 
    base_price, 
    price_unit, 
    duration, 
    guarantee, 
    policies, 
    is_active, 
    created_at, 
    updated_at
) VALUES 
(
    'Plomberie',
    'سباكة',
    'Services de plomberie professionnels incluant réparation de fuites, installation de robinets, réparation de chauffe-eau et maintenance des systèmes d''égout. Intervention rapide et garantie qualité.',
    'خدمات سباكة احترافية تشمل إصلاح التسريبات وتركيب الحنفيات وإصلاح سخانات المياه وصيانة أنظمة الصرف الصحي. تدخل سريع وضمان الجودة',
    'Plomberie',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    1500.00,
    'par heure',
    '1-3 heures',
    '6 mois',
    'Intervention sous 24h, devis gratuit, garantie pièces et main d''œuvre, paiement sécurisé après validation du travail, nettoyage du chantier inclus.',
    true,
    NOW(),
    NOW()
),
(
    'Électricité',
    'كهرباء',
    'Services électriques complets : installation électrique, réparation de panneaux, éclairage LED, sécurité électrique et maintenance préventive. Techniciens certifiés.',
    'خدمات كهربائية شاملة: التركيب الكهربائي وإصلاح لوحات التوزيع والإضاءة LED والأمان الكهربائي والصيانة الوقائية. فنيون معتمدون',
    'Électricité',
    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&crop=center',
    2000.00,
    'par heure',
    '2-4 heures',
    '12 mois',
    'Techniciens certifiés, diagnostic gratuit, respect des normes de sécurité, garantie complète sur tous travaux, matériaux de qualité supérieure.',
    true,
    NOW(),
    NOW()
),
(
    'Peinture',
    'دهان',
    'Services de peinture intérieure et extérieure, préparation des surfaces, finitions décoratives et rénovation complète des murs et plafonds. Peintures écologiques disponibles.',
    'خدمات الدهان الداخلي والخارجي وإعداد الأسطح والطلاءات الزخرفية والتجديد الكامل للجدران والأسقف. دهانات صديقة للبيئة متوفرة',
    'Peinture',
    'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&h=600&fit=crop&crop=center',
    800.00,
    'par m²',
    '1-3 jours',
    '3 ans',
    'Peintures écologiques disponibles, nettoyage inclus, protection des meubles, satisfaction garantie, finitions soignées, couleurs personnalisées.',
    true,
    NOW(),
    NOW()
),
(
    'Climatisation',
    'تكييف',
    'Installation, réparation et maintenance de systèmes de climatisation et chauffage, nettoyage des filtres et optimisation énergétique. Service d''urgence 24/7 disponible.',
    'تركيب وإصلاح وصيانة أنظمة التكييف والتدفئة وتنظيف المرشحات وتحسين كفاءة الطاقة. خدمة طوارئ متوفرة على مدار الساعة',
    'Climatisation',
    'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=600&fit=crop&crop=center',
    3000.00,
    'par intervention',
    '2-6 heures',
    '18 mois',
    'Service d''urgence 24/7, pièces d''origine, maintenance préventive incluse, économies d''énergie garanties, diagnostic complet gratuit.',
    true,
    NOW(),
    NOW()
),
(
    'Menuiserie',
    'نجارة',
    'Fabrication et réparation de meubles sur mesure, portes, fenêtres, escaliers et aménagements intérieurs en bois de qualité. Design personnalisé et finitions soignées.',
    'تصنيع وإصلاح الأثاث المخصص والأبواب والنوافذ والسلالم والتجهيزات الداخلية من الخشب عالي الجودة. تصميم مخصص وطلاءات دقيقة',
    'Menuiserie',
    'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop&crop=center',
    2500.00,
    'par projet',
    '3-7 jours',
    '5 ans',
    'Bois certifiés, design personnalisé, finitions soignées, garantie structurelle longue durée, conseils d''entretien inclus.',
    true,
    NOW(),
    NOW()
),
(
    'Maçonnerie',
    'بناء',
    'Construction et rénovation de murs, fondations, terrasses, allées et structures en béton avec matériaux durables. Respect des normes de construction.',
    'بناء وتجديد الجدران والأساسات والتراسات والممرات والهياكل الخرسانية باستخدام مواد متينة. احترام معايير البناء',
    'Maçonnerie',
    'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=600&fit=crop&crop=center',
    1200.00,
    'par m²',
    '2-5 jours',
    '10 ans',
    'Matériaux certifiés, respect des normes de construction, suivi de chantier, garantie structurelle décennale, nettoyage complet.',
    true,
    NOW(),
    NOW()
),
(
    'Nettoyage',
    'تنظيف',
    'Services de nettoyage professionnel : nettoyage résidentiel, commercial, après rénovation et entretien régulier des locaux. Produits écologiques et personnel formé.',
    'خدمات التنظيف الاحترافية: التنظيف السكني والتجاري وبعد التجديد والصيانة الدورية للمباني. منتجات صديقة للبيئة وموظفون مدربون',
    'Nettoyage',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    500.00,
    'par heure',
    '2-8 heures',
    'Satisfaction',
    'Produits écologiques, personnel formé, satisfaction garantie, nettoyage en profondeur inclus, matériel professionnel, horaires flexibles.',
    true,
    NOW(),
    NOW()
),
(
    'Jardinage',
    'بستنة',
    'Entretien des jardins, aménagement paysager, taille des arbres, irrigation automatique et création d''espaces verts. Plantes adaptées au climat local.',
    'صيانة الحدائق وتنسيق المناظر الطبيعية وتقليم الأشجار والري التلقائي وإنشاء المساحات الخضراء. نباتات متكيفة مع المناخ المحلي',
    'Jardinage',
    'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&h=600&fit=crop&crop=center',
    800.00,
    'par heure',
    '2-6 heures',
    'Saison',
    'Plantes adaptées au climat, entretien saisonnier, conseils personnalisés, garantie de reprise, irrigation intelligente, design paysager.',
    true,
    NOW(),
    NOW()
),
(
    'Serrurerie',
    'قفل',
    'Ouverture de portes, changement de serrures, installation de systèmes de sécurité, clés de secours et dépannage d''urgence. Intervention rapide 24/7.',
    'فتح الأبواب وتغيير الأقفال وتركيب أنظمة الأمان والمفاتيح الاحتياطية وإصلاح الطوارئ. تدخل سريع على مدار الساعة',
    'Serrurerie',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    2500.00,
    'par intervention',
    '30 min - 2h',
    '12 mois',
    'Intervention d''urgence 24/7, serrures certifiées, sécurité renforcée, garantie sur pièces et main d''œuvre, clés de secours.',
    true,
    NOW(),
    NOW()
),
(
    'Vitrerie',
    'زجاج',
    'Remplacement de vitres cassées, installation de vitres isolantes, miroirs, vitrines commerciales et réparation d''urgence. Vitres de sécurité et isolation thermique.',
    'استبدال الزجاج المكسور وتركيب الزجاج العازل والمرايا والواجهات التجارية والإصلاح الطارئ. زجاج أمان وعزل حراري',
    'Vitrerie',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    1800.00,
    'par m²',
    '1-4 heures',
    '6 mois',
    'Vitres de sécurité, isolation thermique, intervention rapide, garantie anti-casse, nettoyage professionnel, finitions soignées.',
    true,
    NOW(),
    NOW()
);

-- Verify the insertion
SELECT 
    id,
    name,
    name_ar,
    category,
    base_price,
    price_unit,
    duration,
    guarantee,
    is_active,
    created_at
FROM services 
ORDER BY id;
